# Generated by Django 3.2 on 2022-12-06 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Outsource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientaddress_link', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='clientaddress_link', to='test3.test')),
            ],
        ),
    ]
