# Generated by Django 3.2 on 2022-12-06 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test3', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outsource',
            old_name='clientaddress_link',
            new_name='link',
        ),
    ]
