# Generated by Django 3.2 on 2022-12-29 20:58

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('test3', '0002_rename_clientaddress_link_outsource_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='manytomany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('fieldname', models.CharField(default=None, max_length=80)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='test3.manytomany')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='test',
            name='quantity',
        ),
        migrations.DeleteModel(
            name='Outsource',
        ),
        migrations.AddField(
            model_name='test',
            name='interest_in_link',
            field=models.ManyToManyField(blank=True, default=None, related_name='interest_in_link', to='test3.manytomany'),
        ),
    ]
